### PR TITLE
SwiftUI Example

### PR DESCRIPTION
**Pull request by AndrewSB**
This depends on #159, the first three commits in here are from there

### CODE REVIEW

**Comment by AndrewSB** [comment]
Follow up to #131, it looks like using the InputBarAccessoryView in SwiftUI leads to the bottom input stack view to have a height of 331. Not sure why.

Screen Shot 2020-10-03 at 10 51 24 PM

The example in MessageKit doesn't allow the table to be written in SwiftUI

**Comment by Kaspik** [comment]
Rebase and update if still valid please :)

**Comment by AndrewSB** [comment]
rebased - there are no merge conflicts with `nathantannar4:master` when I check locally... i don't understand why GitHub thinks there are conflicts

**Comment by Kaspik** [comment]
Try to merge the master--- not sure what's going on

**Review by Kaspik — APPROVED** [review]

**Comment by AndrewSB** [comment]
_one year later_

**Comment by AndrewSB** [comment]
kidding, thanks for taking the time to close this out 😝

**Pull request merged**
