### PR TITLE
Support Swift Package Manager

### PR DESCRIPTION
**Pull request by Nixon506E**

### CODE REVIEW

**Comment by Kaspik** [comment]
@nathantannar4 Is this correct actually? Do yo ureally want to have RxSwift as dependency for everyone?

We should move RxSwift to subdependency / submodule and not have it inside IBAV. Right now for example everyone who installs MessageKit will also have RxSwift even tho he doesn't need that... :(

**Comment by nathantannar4** [comment]
When I tested this, RxSwift does not get pulled in as a dependency for my project if I don't select the RxExtensions target when adding the Swift Package through Xcode. The source gets downloaded which is unfortunate, but I don't think SPM supports a "subspec" equivalent yet? Open to ideas on how to better manage this.

**Comment by Kaspik** [comment]
Yeah, SPM doesn't support this yet.
I was thinking about separate subsepc/podspec/package like RxInputBarAccessoryView? That one would have main InputBarAccessoryView as a dependency - so it would be vice-versa as it is now. Who wants both - will target to that and it will get automatically both, who wants only IBAV then he will target only to main one.

I know splitting sucks, on the other hand maintaining that one would be easier as it would me super small code with depencency on main code/framework.

**Comment by nathantannar4** [comment]
Would splitting mean we need 2 repos? 

Im also open to just removing the RxSwift extensions by default and if a SPM user wants it they can just add the one file to their project. Its also not ideal, but that's what Carthage users have to do I think

**Comment by Kaspik** [comment]
No, we can leave it in this one, just in separate folder, where in that folder there will be separate podspec and package file.

Yes, we can also remove it for now.

**Comment by Kaspik** [comment]
Actually, taking it back - it can't be in subfolder. :( 

https://stackoverflow.com/a/50095567/4927614

**Pull request merged**
