### PR TITLE
adjusts backgroundView constraints from bottom anchor of topStackView…

### PR DESCRIPTION
**Pull request by travischapman**
… to top anchor of inputBarAccesoryView

### CODE REVIEW

**Comment by nathantannar4** [comment]
@travischapman The background view is intentionally anchored to the bottom of the top stack view. 

Why?
Say for example you want to place a custom view in the top of the input bar and have a transparent background, but you want there to be a background color behind the text view, send button, etc. This easily allows you to have the background color of the `InputBarAccessoryView` to be .clear while the `backgroundView` being your actual background color. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
Note that I document (comment) the positioning of the backgroundView where it is defined

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nathantannar4** [comment]
Do you have a screenshot?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by travischapman** [comment]
No, I figured out another solution without using translucency. Thanks

**Pull request closed without merging**
